### ISSUE TITLE
The popup is not fully opened

### ISSUE THREAD

**Issue by hanhpv** [AliasIO/Wappalyzer#1578] opened 2017-05-19 01:57 UTC
On Chrome for macOS Sierra 10.12.4

On the first click, the popup is not fully opened:
<img width="289" alt="screen shot 2017-05-19 at 8 53 34 am" src="https://cloud.githubusercontent.com/assets/5069672/26230146/fbb0d092-3c70-11e7-8879-16e797030a16.png">

I have to click a few times for it to be fully expanded:
<img width="265" alt="screen shot 2017-05-19 at 8 56 30 am" src="https://cloud.githubusercontent.com/assets/5069672/26230164/14b75fe8-3c71-11e7-9e1c-53706200adbd.png">

**Comment by natematykiewicz** [comment] 2017-05-21 03:35
This is a duplicate of #1510.

**Closed** 2017-06-11 05:31 UTC
