### ISSUE TITLE
Not displaying any technologies on version 5.1

### ISSUE THREAD

**Issue by calicubilly** [AliasIO/wappalyzer#3119] opened 2020-05-28 04:12 UTC
**Platform**
Which platform does the bug apply to?
* Microsoft Edge Version 83.0.478.37

**Describe the bug**
Not displaying any technologies after update to version 5.10

**To Reproduce**
1. Open Microsoft Edge
2. Go to any website
3. Click on the wappalyzer icon
4. See error, no technologies displayed

**Expected behavior**
Detected technologies should be displayed

**Additional context**
- None
<img width="1241" alt="Screen Shot 2020-05-28 at 12 10 17 PM" src="https://user-images.githubusercontent.com/46476701/83098072-39ba9580-a0dc-11ea-9234-66cde1634258.png">

**Comment by AliasIO** [comment] 2020-05-28 04:22
Duplicate of #3118

**Closed by AliasIO** 2020-05-28 04:22 UTC
Labels: Bug

**Comment by calicubilly** [comment] 2020-06-02 09:21
it's not working again sir @AliasIO 

<img width="871" alt="Screen Shot 2020-06-02 at 5 20 07 PM" src="https://user-images.githubusercontent.com/46476701/83503352-8562aa00-a4f5-11ea-9c69-5e19754d3b80.png">
