### ISSUE TITLE
Not detecting OctoberCMS

### ISSUE THREAD

**Issue by FlusherDock1** [AliasIO/wappalyzer#2920] opened 2020-01-24 09:52 UTC
**Platform**
WebExtension (Google Chrome, Mozilla Firefox)

**Describe the bug**
Extension didn't detecting OctoberCMS

**To Reproduce**
1. Go to https://octobercms.com/
2. See error

**Expected behavior**
Should detect by cookies.

**Comment by swiper** [comment] 2020-02-05 14:43
This can be fixed by merging #2928, which fixes the cookie name value.

**Comment by kyletaylored** [comment] 2021-02-02 18:19
The detection works as designed, the problem is that the home page does not initiate a cookie, you must first go to an account or registration page to initialize a cookie.

https://octobercms.com/account/register

**Closed by kyletaylored** 2021-02-02 18:19 UTC
Labels: Bug
