### ISSUE TITLE
Many false positives on 5.3.2 -- http://speedtest.att.com/speedtest/

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#1969] opened 2017-12-28 15:45 UTC
Confirmed in...
Windows 8.1
FireFox Developer 58.0b12 (64-bit)
Chrome 63.0.3239.84 (Official Build) (64-bit)
Wappalyzer v5.3.2

http://speedtest.att.com/speedtest/

CMS
AMPcms
AsciiDoc
Backdrop
Bubble
Concrete5
DNN true
DataLife Engine
DedeCMS
Jimdo
Joomla
Liferay
Lithium
LiveStreet CMS
MODX
Methode
Microsoft SharePoint
Mono.net
Pligg
Posterous
Proximis Omnichannel
Rayo
Squarespace
Stackla Social Hub
Telescope
TiddlyWiki
Umbraco
Ushahidi
VIVVO
Wix
WordPress
XOOPS
actionhero.js
eSyndiCat
phpCMS
Message Board
Discourse
Discuz! X discuzVersion
IPB
Mattermost
MyBB
Reddit
SMF
TiddlyWiki
phpBB
vBulletin
Database Manager
Bablic
Bubble
phpMyAdmin
Documentation Tool
Adobe RoboHelp
Sphinx
TiddlyWiki
Widget
AddThis
AddToAny
Hello Bar
Klarna Checkout
Outbrain
Po.st
ShareThis
Shopalize
Stackla
Ecommerce
Avangate
Bizweb
CS Cart
Comandia
Gambio
Haravan
Kamva
Klarna Checkout
KobiMaster
Magento
Neto
OXID eShop
PrestaShop (25% sure)
Proximis Omnichannel
Robin
Salesforce Commerce Cloud
Sazito
Shopatron
Shopify
Shoptet
TomatoCart
UltraCart
Volusion
WEBXPAY
WooCommerce
X-Cart
Yahoo! Ecommerce
Jetshop
Photo Galleries
Gallery
Wikis
Foswiki
MoinMoin
TiddlyWiki
Hosting Panels
Bablic
Analytics
SiteCatalyst
Google Analytics Enhanced eCommerce
AT Internet Analyzer
AT Internet XiTi
BugSense
BugSnag
Chartbeat
ClickHeat
ClickTale
Clicky
Crazy Egg
Cross Pixel
Gauges
GoStats
Google Analytics
Gravity Insights
Heap
Hotjar
INFOnline
Intercom
Jirafe
KISSmetrics
Kampyle
Luigi’s Box
Mint
Mixpanel
Nedstat
Netmonitor
New Relic
OneAPM
OneStat
Open Web Analytics
Optimizely
Parse.ly
Piwik
Quantcast
Reinvigorate
Segment
ShinyStat
Shopalize
Snoobi
Tealeaf
TrackJs
UserEngage
Webtrekk
Webtrends
Yahoo! Web Analytics
Yandex.Metrika
comScore
GoSquared (30% sure)
Inspectlet
Mouse Flow
Visual Website Optimizer
Blog
Posterous
Typecho
WordPress
JavaScript Framework
Prototype
jQuery
jQuery UI 1.8.11
AlloyUI
AngularJS true
Backbone.js true
Catberry.js true
Deployd
Dojo true
ef.js true
Ember.js true
Enyo
ExtJS true
Fingerprintjs
Hammer.js true
Handlebars true
HeadJS
Hogan.js
Immutable.js true
InfernoJS true
Knockout.js true
List.js
Marionette.js true
Meteor
MochiKit
Modernizr
Moment.js
MooTools
Mustache
Neonclear
OpenUI5
Petrojs
Phaser
Polymer
React
RequireJS
Reveal.js
RightJS
Riot
RxJS (20% sure)
Snap.svg
Socket.io (20% sure)
SoundManager
styled-components
SweetAlert
TweenMax
Twitter Flight
Twitter typeahead.js
Vue.js
Webix
Wink
XRegExp
YUI
Zepto
basket.js (20% sure)
math.js
prettyPhoto
script.aculo.us
Underscore.js
Issue Tracker
Atlassian Jira
Get Satisfaction
GitLab
Kampyle
Taiga
Usabilla
UserRules
UserVoice
Video Player
Asciinema
MediaElement.js true
SublimeVideo
VideoJS
Comment System
Disqus
Livefyre true
Captcha
Captch Me
Solve Media
reCAPTCHA
Font Script
Cufon
Google Font API
Typekit
Web Framework
Adobe ColdFusion
Angular Material
Apache Wicket
Bubble
Catberry.js true
Django
Google Web Toolkit
Kendo UI true
Nette Framework
Next.js
Penguin
Shapecss
Visual WebGUI
Yii
actionhero.js
Bootstrap
Microsoft ASP.NET
Ruby on Rails
Miscellaneous
SWFObject
CodeMirror true
EPrints
Google Code Prettify
Gravatar
JobberBase
K2
PDF.js
Prefix-Free
Prism
SobiPro
SyntaxHighlighter
Zabbix
Highlight.js
Editor
AsciiDoc
LMS
Moodle
Web Server
Bubble
Next.js
actionhero.js
Apache
IIS
Rich Text Editor
CKEditor true
Etherpad
FreeTextBox
Quill
TinyMCE
JavaScript Graphics
Chart.js
D3 true
Exhibit true
Google Charts
Highcharts true
JS Charts
JavaScript Infovis Toolkit true
KineticJS true
MathJax true
NVD3 (20% sure)
Plotly
Protovis
Raphael
Rickshaw
Timeplot
Twitter Emoji (Twemoji)
amCharts
shine.js
three.js
xCharts
Mobile Framework
Enyo
Mobify
Wink
jQTouch
Programming Language
AsciiDoc
PHP
CFML
Java
Python
Node.js
Perl
Go
Ruby
Operating System
Windows Server
Search Engine
Algolia Realtime Search
Luigi’s Box
Swiftype
Web Mail
Outlook Web App
RainLoop
RoundCube
SquirrelMail
CDN
ArvanCloud
CloudFlare
Marketing Automation
Act-On
Bounce Exchange
Eloqua
HubSpot
Jirafe
Marketo
Pardot
RD Station
Mautic
Database
MySQL
MongoDB
Map
OpenLayers
Ushahidi
Advertising Network
Prebid
AdRiver
AdRoll
Adcash
Advert Stream
Adzerk
BittAds
BuySellAds
Captch Me
Carbon Ads
Chitika
Criteo
Epom
Fusion Ads
Google AdSense
LinkSmart
MadAdsMedia
Open AdStream
Project Wonderful
Smart Ad Server
Solve Media
Tealium
Titan
Veoxa
VigLink
Yahoo Advertising
Yandex.Direct
Zanox
Payment Processor
Klarna Checkout
Braintree
PayPal
Stripe
Tag Manager
Google Tag Manager
Paywall
Piano Solo
Build/CI System
webpack
Remote Access
ShellInABox
Development Tool
Artifactory
Atlassian Bitbucket
PHPDebugBar
Gerrit
GitLab
SonarQubes
styled-components
git
Live Chat
LiveAgent
Raychat
GoSquared (30% sure)
CRM
Salesforce
GoSquared (30% sure)
Cloudcoins
CoinHive
Coinlab
Crypto-Loot
Inwemo
JSEcoin
ProjectPoi

**Comment by jvoisin** [comment] 2017-12-28 15:57
I can't reproduce on [the website]( https://www.wappalyzer.com/ ), but I've got the same results in my browser :D

**Comment by AliasIO** [comment] 2017-12-28 22:43
Fun one. That site overrides native functions such as `Object.keys` and `Array.prototype.reduce`, which interferes with the injected script. I've rewritten the code so it doesn't call any object or array functions.

Fixed in 4bbda8916b007f6d125bac5e73950d10e2fe2d85.

**Closed by AliasIO** 2017-12-28 22:43 UTC
