### ISSUE TITLE
Not working with facebook

### ISSUE THREAD

**Issue by rbhatia46** [AliasIO/Wappalyzer#1648] opened 2017-07-17 12:26 UTC
A great tool and very useful but it does not show any technology on facebook.com and it does not work there.

**Comment by gadcam** [comment] 2017-07-17 12:27
Could give your OS, browser with version and Wappalyzer version ? It is working for me on Firefox 54.0.1 (Win 64) with Wappalyzer version 4.1.5.

**Comment by AlexByte** [comment] 2017-07-18 03:13
Duplicate https://github.com/AliasIO/Wappalyzer/issues/1580

**Comment by rbhatia46** [comment] 2017-07-23 12:06
Works now but showing only RxJS and no other technology. I am using Chrome browser.

**Comment by vaidas-lungis** [comment] 2017-08-24 08:44
Duplicate of https://github.com/AliasIO/Wappalyzer/issues/1580

**Comment by AlexByte** [comment] 2017-08-24 11:27
@vaidas-lungis I already wrote it.

**Closed** 2017-11-03 01:52 UTC
