### ISSUE TITLE
Extension merges results of two pages or more

### ISSUE THREAD

**Issue by Varulv1997** [AliasIO/wappalyzer#4017] opened 2021-06-17 21:03 UTC
**Platform**
Which platform does the bug apply to?
Google Chrome

**Describe the bug**
Before update **6.7.4** loading pages would display the technologies used in the extension normally, this current update merges results of multiple pages and shows technologies of other pages into different pages.

For example, visiting YouTube then visiting GitHub would result in the extension displaying YouTube's technologies on the GitHub page (YouTube uses Polymer and the Google Fonts API, unlike GitHub).

![image](https://user-images.githubusercontent.com/31771137/122471542-4e075400-cfb7-11eb-9741-62ee5fe020cb.png)

**To Reproduce**
1. Visit any page and note its technologies
2. Visit a different page with different technologies
3. Clicking the extension icon will show both pages' technologies or more

**Expected behavior**
Displaying only the technologies of the current page

**Comment by AliasIO** [comment] 2021-06-17 21:40
Duplicate of #4005. I haven't been able to reproduce this yet.

**Closed by AliasIO** 2021-06-17 21:40 UTC
Labels: Bug
