### ISSUE TITLE
need some option for deeply analyzing html content

### ISSUE THREAD

**Issue by hbakhtiyor** [AliasIO/Wappalyzer#2218] opened 2018-04-09 13:40 UTC
the current is [hard coded](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/driver.js#L221), and can't recognize some apps, need some option or optimization algorithm for recognizing it. 

```
      if ( html.length > 50000 ) {
        html = html.substring(0, 25000) + html.substring(html.length - 25000, html.length);
      }
```

**Comment by gadcam** [comment] 2018-04-09 13:50
Duplicate of #1614.

**Closed** 2018-04-12 15:53 UTC

**Comment by AliasIO** [comment] 2018-04-20 23:25
I'm adding `htmlMaxCols` and `htmlMaxRows` options to configure this in the next version.
