### ISSUE TITLE
Add option to show Wappalyzer icon inside the url bar (beside the star in Chrome).

### ISSUE THREAD

**Issue by josephan** [AliasIO/Wappalyzer#1112] opened 2016-03-03 01:14 UTC
It's just a personal preference. I think it looks cleaner that way.
I will take a stab at it.

**Comment by Triloworld** [comment] 2016-03-03 07:37
I confirm: 
Chrome 49.0.2623.75 m
No icons in adress bar. It works, it was usefull and pleas, bring it back!

**Comment by okaufmann** [comment] 2016-03-03 10:21
Same here in chrome 48.0.2564.116 m

**Comment by azinasili** [comment] 2016-03-03 14:11
Not sure what changed, but I also would love the icon to move back into the address bar.

**Comment by erickrawczyk** [comment] 2016-03-03 15:04
duplicate of #1110

**Closed** 2016-03-03 15:10 UTC
