### ISSUE TITLE
 Extension buttons in URL bar aren't showing in pop-up windows

### ISSUE THREAD

**Issue by radriaanse** [AliasIO/Wappalyzer#841] opened 2015-04-10 17:31 UTC
When a window is showing up as a pop-up windows (but with an URL bar), the extension buttons don't appear. 
Other extensions do appear, so it seems that it's only a problem with this one. 

Tested on;
OS: Archlinux
Browser: Firefox 37.0.1
Window manager: i3-wm (v. 4.10.1) & Cinnamon (v. 2.4.8)
Add-on: Wappalyzer (v. 3.0.15)

**Comment by klonos** [comment] 2015-06-19 23:24
Example URL please?

**Comment by dfrankland** [comment] 2015-06-20 00:59
Easy way of testing this:
1. Into your URL bar type: `javascript:`
2. Copy and paste: `window.open("http://google.com","Google",'left=0,top=0,width=1024,height=640');`
3. Hit Enter.

**Comment by dfrankland** [comment] 2015-06-20 01:11
Open the Web Console (Command + Alt + K) and type in:
```window.open("http://www.google.com","Google","height=680,width=1024")```

**Comment by dfrankland** [comment] 2015-06-20 01:12
Open the Web Console (Command + Alt + K) and type in:
`window.open("http://www.google.com","Google","height=680,width=1024");`

**Comment by klonos** [comment] 2015-06-20 04:48
Oh, you're right that the icons don't show up there, but then again the URL bar in those windows is in a special/disabled state. That might be the cause.

**Comment by radriaanse** [comment] 2015-10-25 14:49
What is the reason for not fixing this?

**Comment by AliasIO** [comment] 2015-10-25 23:07
Sorry, I didn't mean to close this one.

**Comment by radriaanse** [comment] 2015-10-26 09:29
cool :)

**Closed** 2016-06-19 01:28 UTC
