### ISSUE TITLE
Dropdown from Wappalyzer Icon Broken on Many Websites in Chrome

### ISSUE THREAD

**Issue by PatriotRDX** [AliasIO/Wappalyzer#1510] opened 2017-04-06 16:43 UTC
The dropdown display that appears when you click on the icon in Chrome is broken. It flashes for about a half second and then collapses so that you can only see one of the listed items. There's no way for you to see the rest of the items.

The weird thing is that sometimes it *does* work. I've attached two screenshots below that showcase what I'm talking about. One that is listed as "broken" and one that is listed as "not-broken". This is not my website, it's from the University of Cincinnati, although, this does happen on other sites as well.

I haven't encountered this issue in Firefox yet. Although it's possible I've been lucky so far using that browser.

I also want to note that I have tried disabling each extension and nothing changes this behavior in Wappalyzer.

# Extensions I have installed on Chrome
* Accessibility Developer Tools
* Application Launcher for Drive (by Google) (Disabled)
* aXe
* Full Page Screen Capture
* Go Back with Backspace
* Google Docs
* Google Docs Offline (Disabled)
* Google Sheets
* Google Slides
* LastPass: Free Password Manager
* lipsum.com extension
* Page Analytics (by Google) (Disabled)
* uBlock Origin
* Wappalyzer
* Web Developer

# Broken
<img width="561" alt="Broken version of the Wappalyzer plugin in Chrome." src="https://cloud.githubusercontent.com/assets/23663019/24765423/b7be8cb6-1ac5-11e7-84c0-2962e25cebb5.png">

# Not Broken
<img width="507" alt="Non-broken version of the Wappalyzer plugin in Chrome." src="https://cloud.githubusercontent.com/assets/23663019/24765425/ba05066c-1ac5-11e7-8546-0d740eeedb03.png">

**Comment by edmandiesamonte** [comment] 2017-04-07 08:29
Adding issue scenario sample in GIF 

![GIF Sample](https://media.giphy.com/media/3oKIPA4SFJWJmHqcms/giphy.gif)

**Comment by RezaGhanbari** [comment] 2017-04-07 18:17
Same error for me ,after upgrading to 4th version.

Chrome extensions:
Chameleon
JSON Viewer

**Comment by DaAwesomeP** [comment] 2017-04-08 23:04
@PatriotRDX, @edmandiesamonte, @RezaGhanbari What version of Chrome do you have? You all seem to be on Mac OS. Also, please look around in the debugger for CSS or markup issues if you may: https://developer.chrome.com/extensions/tut_debugging#inspect-popup

**Comment by PatriotRDX** [comment] 2017-04-08 23:27
@DaAwesomeP I have the latest stable version, no Beta updates or anything along those lines...same with the extensions... I'll need to wait until I get back to work on Monday to try inspecting the pop-up.

**Comment by RezaGhanbari** [comment] 2017-04-09 06:25
@DaAwesomeP Chrome version  55.0.2883.95 (64-bit) on macOS Sierra.
I also checked on Windows 8.1 and Ubuntu 16.04. That was okay.

**Comment by DaAwesomeP** [comment] 2017-04-09 19:26
@PatriotRDX @RezaGhanbari Thanks for checking! It's either that CSS file issue or another known Chromium issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=307912

https://bugs.chromium.org/p/chromium/issues/detail?id=428044

https://bugs.chromium.org/p/chromium/issues/detail?id=317880

https://github.com/gorhill/uMatrix/issues/423

On 4/9/17 1:25, Reza wrote:

@DaAwesomeP<https://github.com/DaAwesomeP> Chrome version 55.0.2883.95 (64-bit) on macOS Sierra.
I also checked on Windows 8.1 and Ubuntu 16.04. That was okay.

**Comment by PatriotRDX** [comment] 2017-04-10 17:28
@DaAwesomeP inspecting did not turn up much besides the console message that @RezaGhanbari found, that `chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/css/widgets.css` was missing.

Granted I don't know a lot about Chrome development, since I'm just a regular old web designer/dev, but maybe this was a built-in file that was removed from Chrome on Mac for whatever reason?

**Comment by DaAwesomeP** [comment] 2017-04-10 22:12
I appear to be reeving the same error on Windows, but I don't have any issues. I don't think that `widget.css` is really meant to exist anymore. It's probably residue in the HTML from the older Chrome-only driver. There is some other issue here.
![wappwidget](https://cloud.githubusercontent.com/assets/4472083/24884691/3f3adad0-1e10-11e7-80c9-71a278e2a44a.PNG)

Could you attach the extension file (in a ZIP or other archive) as it appears on your system? It should be the folder at `~/Library/Application Support/Google/Chrome/Default/Extensions/gppongmhjkpfnbhagpmjfkannfbllamg`. 

Have you tried completely uninstalling and reinstalling the extension? I don't have a Mac, so I can't reproduce this issue.

The only (and unrelated) issue I have on Chrome for Windows is that Chrome sometimes butchers the box shadow on the popup and just shows an ugly, thick black border.

**Comment by RezaGhanbari** [comment] 2017-04-11 09:34
@DaAwesomeP Yes I have tried completely uninstalling and reinstalling.
There is a link to widgets.css in popup.html but widgets.css file does not exist.



<img width="1280" alt="screen shot 2017-04-11 at 2 01 12 pm" src="https://cloud.githubusercontent.com/assets/11388205/24902449/64838b5c-1ebf-11e7-8ac9-5e7e22d87cc2.png">


[4.0.1_0.zip](https://github.com/AliasIO/Wappalyzer/files/912731/4.0.1_0.zip)

**Comment by dmetzler1988** [comment] 2017-04-12 16:08
Same issue here with Chrome 57.0.2987.133 on MacOS. 
Need to click multiple on icon to show popup with info till the info will be shown correctly.  

Same behavior on my macbook pro with same Chrome version.

**Comment by DaAwesomeP** [comment] 2017-04-12 23:45
@RezaGhanbari Yes, `widgets.css` doesn't even exist in the source, but that is not the cause of the problem. There used to be a `widgets.css`, but it's not needed anymore. It's just still referenced in the HTML by mistake. I have a strong feeling that this is a very specific issue with Chrome for Mac.

@AliasIO thoughts?

**Comment by RezaGhanbari** [comment] 2017-04-13 04:42
@DaAwesomeP yes , it is a wrong reference in popup.html

**Comment by PatriotRDX** [comment] 2017-04-13 16:29
@DaAwesomeP I did uninstall/reinstall. I've attached the extension in a .zip file for you.
[gppongmhjkpfnbhagpmjfkannfbllamg.zip](https://github.com/AliasIO/Wappalyzer/files/920260/gppongmhjkpfnbhagpmjfkannfbllamg.zip)

**Comment by AliasIO** [comment] 2017-04-14 00:23
Perhaps the issue is that Wappalyzer changes the height of the popup (by adding applications as it find it) during the opening animation on OS X.

**Comment by PatriotRDX** [comment] 2017-04-14 01:34
@AliasIO the weird thing is that sometimes it does work. And the extension used to work...and now I wish I knew which version started this. Definitely after the logo change went into effect though.

**Comment by AliasIO** [comment] 2017-04-14 02:11
It could just be timing. There have only been slight CSS changes to the pop-up CSS, nothing major.

**Comment by petercunha** [comment] 2017-04-25 23:57
Same issue here on MacOS, Chrome 58.0.3029.81, and Wappalyzer 4.0.1. This bug is really annoying, hopefully there'll be a fix for it soon.

**Comment by kstratis** [comment] 2017-04-27 05:48
Same here too. MacOS, Chrome Version 58.0.3029.81 (64-bit) and Wappalyzer 4.0.1. It happens all the time and you simply can't read the list. Such an awful glitch...

**Comment by deanylev** [comment] 2017-04-28 07:50
Same issue here, Chrome 57 on macOS. Makes my favourite extension unusable :(

**Comment by PatriotRDX** [comment] 2017-04-28 20:03
@AliasIO were there any changes in code other than CSS? Perhaps in the Javascript that for some reason Chrome does not like?

**Comment by AliasIO** [comment] 2017-04-29 01:22
Chrome uses the polyfill now, and promises to query the tabs. That may be causing a timing issue. I can reproduce the issue but very inconsistently, perhaps one out of ten times when I click the icon to expand the popup.

**Comment by AliasIO** [comment] 2017-04-29 06:38
I rewrote most of the popup code in 70ecdf0899d7e4b02c866dbd1a31847f4acf96a7, hopefully it's better now. There are two asynchronous calls that happen; one to get the active tab and one to get the detected applications. Previously they fired on document ready. Now they fire immediately, which means the markup is in the popup earlier (and gets updated only once instead of once for each application to further reduce flashing). I'm also forcing a redraw of the popup after 600ms in case it does get stuck.

**Comment by kstratis** [comment] 2017-05-15 06:29
I can confirm that the problem is still there after upgrading to the latest version v4.1.0.

**Comment by deanylev** [comment] 2017-05-15 12:42
Happens less frequently now, but definitely still happens.

**Comment by sgnl** [comment] 2017-05-24 22:39
I am experiencing this issue with this site: https://www.ymcahnlonlinereg.org/Activities/ActivitiesAdvSearch.asp

**Comment by bitclaw** [comment] 2017-05-25 15:40
It's happening in several sites for me, for example:

http://www.internetbrands.com/
https://trprize.org/
www.google.com

..etc.

**Comment by mr-devboy** [comment] 2017-05-27 15:01
Have the same issue
MacOS 10.12 / Chrome 58

**Comment by PatriotRDX** [comment] 2017-05-27 20:26
@AliasIO @DaAwesomeP I haven't experienced a problem for the past several days. Everything seems to be resolved. Perhaps the other people haven't updated yet? I'll keep checking just in case.

**Comment by jswny** [comment] 2017-05-28 17:52
I'm definitely still having the same problem on many sites.

MacOS 10.12.4 / Chrome 58

**Comment by kstratis** [comment] 2017-06-01 12:25
@jswny I second that! It's exactly what's happening to me too!
The popup is totally broken. 

MacOS 10.12.5/ Chrome 58.0.3029.110 (64-bit) / Wappalyzer 4.1.2

**Comment by DaAwesomeP** [comment] 2017-06-07 21:46
@PatriotRDX what version of Wappalyzer, Chrome (specifically), and macOS do you have installed?

**Comment by AliasIO** [comment] 2017-06-11 05:33
I'm trying something else to work around this (99579252d238c8182206f8976e8318a1fe9db88f). The issue is with Chrome on MacOS though.

**Comment by deanylev** [comment] 2017-06-11 06:54
I think that latest update might've done it! Fingers crossed :)

**Comment by Raman-Maan** [comment] 2017-06-13 01:51
I'm still encountering this issue on the latest update, using Chrome on macOS.

**Comment by simonepri** [comment] 2017-06-30 20:38
Same here:
MacOS 10.12.5/ Chrome 60.0.3112.40 (64-bit) / Wappalyzer 4.1.3

**Comment by AliasIO** [comment] 2017-07-30 01:32
Please let me know if this is still happening in version 5.

**Comment by simonepri** [comment] 2017-07-30 07:13
Still happening:
![image](https://user-images.githubusercontent.com/3505087/28751414-2b036b9c-7507-11e7-9e8f-9cb2b1330ec0.png)
(This is on GitHub)

 5.0.3

**Comment by mlbdenver** [comment] 2017-08-01 00:16
I'm having this issue too. Sometimes it works, other times the stack collapses. Also on Chrome on MacOS. (Also, Wappalyzer logo remains in toolbar, despite checking 'Use application icon instead of Wappalyzer logo')
![image](https://user-images.githubusercontent.com/7061877/28803780-3ce2471e-761c-11e7-8f98-5b2fd6230ef3.png)

**Comment by AliasIO** [comment] 2017-08-05 05:29
I'm hopeful that the workaround in c4328afa302c657e796e2889d8cdd06a29e35903 fixes this. Looks out for v5.0.5.

**Comment by simonepri** [comment] 2017-08-05 06:36
@AliasIO still there:
![image](https://user-images.githubusercontent.com/3505087/28993522-1cfb73b2-79b9-11e7-9043-2ecb002b827b.png)

`MacOS 10.12.6/ Chrome 60.0.3112.78 (64-bit) / Wappalyzer 5.0.5`

**Comment by deanylev** [comment] 2017-08-05 06:39
Yep still present.

`macOS 10.12.6 | Chrome 60.0.3112.90 | Wappalyzer 5.0.5`

![image](https://user-images.githubusercontent.com/22049511/28993540-7b96b178-79fc-11e7-92e3-50fbfd04a527.png)

**Comment by deanylev** [comment] 2017-08-05 13:06
@AliasIO Did you mean 5.0.6? So far, every time it seemed like it was about to happen, the popup forced itself open.

**Comment by alayek** [comment] 2017-08-05 22:24
Still present. MacOS 10.12.6, Chrome 60, Wappalyzer 5.0.6.

**Comment by AliasIO** [comment] 2017-08-06 02:24
@deanylev Yes, v5.0.6. It should behave like you said but I'll reopen the issue as it doesn't appear to be working for everyone.

**Comment by AliasIO** [comment] 2017-08-06 02:26
I think it's related to this Chrome issue:
 
https://bugs.chromium.org/p/chromium/issues/detail?id=307912

**Comment by AliasIO** [comment] 2017-08-28 04:43
Fixed in v5.1.0.

**Closed by AliasIO** 2017-08-28 04:43 UTC
