### ISSUE TITLE
Display technologies is broken on most website

### ISSUE THREAD

**Issue by TheophilePACE** [AliasIO/Wappalyzer#1676] opened 2017-08-03 08:47 UTC
On most website, I get some thing like this when I clic on Wappalyzer icon :
<img width="283" alt="screen shot 2017-08-03 at 18 44 34" src="https://user-images.githubusercontent.com/16059672/28913612-ff5fa65e-787b-11e7-9f24-8e1cc2212e10.png">
or : 
<img width="306" alt="screen shot 2017-08-03 at 18 46 29" src="https://user-images.githubusercontent.com/16059672/28913639-1d08e0f8-787c-11e7-9ca4-8484f491363a.png">
<img width="287" alt="screen shot 2017-08-03 at 18 46 21" src="https://user-images.githubusercontent.com/16059672/28913641-1dc0e4c8-787c-11e7-9dde-fa0deef8a5a1.png">

Maybe it is linked with the latest chrome version?

I am on Chrome last version (60.0.3112.78)

**Comment by Empreintes** [comment] 2017-08-03 09:56
same here : 
when i got more than 6 or 7 items, a scrollbar appear before collapse ... 

chrome Version 60.0.3112.78 (Build officiel) (64 bits)
mac os 10.12.5

**Comment by florindediu** [comment] 2017-08-03 12:37
Same here: 
Version 60.0.3112.78 (Official Build) (64-bit)
MacOS Sierra 10.12.5 (16F73)

**Comment by petercunha** [comment] 2017-08-03 19:38
Oh no.... It's happening again :(

Wappalyzer - 5.0.5
Google Chrome - 60.0.3112.90 (64-bit)
MacOS Sierra - 10.12.6

**Comment by Triloworld** [comment] 2017-08-04 10:20
It's because you have enabled 'Hardware Acceleration' in chrome. It will crash all chrome apps popups. In canary they fix it. We wait for this fixes. Meantime: http://www.solveyourtech.com/turn-hardware-acceleration-google-chrome/

Please close topic if solution is working :)

**Comment by florindediu** [comment] 2017-08-04 10:59
@Triloworld - doesn't work.

**Comment by Triloworld** [comment] 2017-08-04 11:39
I have:

Wappalyzer - 5.0.5
Google Chrome - 60.0.3112.90 (64-bit)
MacOS Sierra - 10.12.6

And work just fine. Can you provide link for example site and additional flags enabled chrome://flags ?

**Comment by TheophilePACE** [comment] 2017-08-04 23:24
For example : http://jade.tilab.com/  or http://www.businessinsider.com/

**Comment by AliasIO** [comment] 2017-08-05 04:28
Duplicate of #1510.

**Closed by AliasIO** 2017-08-05 04:28 UTC

**Comment by TheophilePACE** [comment] 2017-08-28 05:15
Hello guys,

I've just seen the new UI and it's beautiful! I have no layout problems anymore and you have done a very nice job in terms of UI. 

Keep on like this,

Thanks for the update!

![image](https://user-images.githubusercontent.com/16059672/29760007-b4c80c3a-8c03-11e7-98da-89155ad70acf.png)
