### ISSUE TITLE
JSON inside iframe

### ISSUE THREAD

**Issue by DenisBitrix** [AliasIO/Wappalyzer#1414] opened 2017-03-06 12:55 UTC
My browser is Chromium 57.0.2986.0 (64-bit).
My issue is similar to https://github.com/AliasIO/Wappalyzer/issues/1407 but in my case some JSON code appears inside an iframe, not in URL.

![screen004](https://cloud.githubusercontent.com/assets/26222175/23610586/ee88fe8e-026a-11e7-828c-0cf4f8b60d8e.png)
Without wappalyzer the page opens fine. With the plugin I click on the help section (as it is shown at the screenshot), then iframe opens fine for a couple of seconds. And finally json appears on the top of it.

To reproduce the problem you can authorize in my test portal.
https://wappalyzer.bitrix24.com/
login: wappalyzer@mailinator.com
password: 123456

**Comment by DenisBitrix** [comment] 2017-03-09 15:21
Any update?

**Comment by AliasIO** [comment] 2017-03-10 23:34
Dupe of #1407.

**Closed by AliasIO** 2017-03-10 23:34 UTC
