### ISSUE TITLE
Multiple 'Set-Cookie' headers not supported in Chrome

### ISSUE THREAD

**Issue by AlexByte** [AliasIO/Wappalyzer#1399] opened 2017-03-01 07:29 UTC
It's because of [chrome/js/driver.js#L132](https://github.com/AliasIO/Wappalyzer/blob/f763a8345985958325cd8378eb64be42a111d750/src/drivers/chrome/js/driver.js#L132) and the same as #1265 and #1213. Analyzed only the last header with same name.

**Comment by AliasIO** [comment] 2017-11-03 01:06
Duplicate of 1213.

**Closed by AliasIO** 2017-11-03 01:06 UTC
