### ISSUE TITLE
Google Search results page detected as Wordpress 4.8.4

### ISSUE THREAD

**Issue by kamtex** [AliasIO/Wappalyzer#1918] opened 2017-12-12 04:56 UTC
When I got to the results page, it detects as wordpress. 
Does not do so for the homepage or for Googe Maps. 
Only results pages.

Tried various search terms and got same results.

Link:
https://www.google.com.sg/search?ei=PWAvWp8Exui-BIT4n_gP&q=espn&oq=espn&gs_l=psy-ab.3..0i131i46i67k1j46i131i67k1l2j0i67k1l3j0i131i67k1j0i67k1l2j0i131k1j0l2.3085.3619.0.3736.4.4.0.0.0.0.81.282.4.4.0....0...1c.1.64.psy-ab..0.4.281....0.M0hwA0MJ1G0
![google-wp](https://user-images.githubusercontent.com/17243028/33868057-b7aefe00-df3b-11e7-9a5c-85677c246a75.png)

https://www.google.com.sg/search?ei=QWAvWs3kDYuAvgTpyafYAw&q=wappalyzer&oq=wapp&gs_l=psy-ab.3.1.0l10.255711.256240.0.257641.4.4.0.0.0.0.132.482.0j4.4.0....0...1c.1.64.psy-ab..0.4.481...0i131i67k1j0i67k1j0i131k1j0i3k1.0.vO3-kId8388

![google-wp2](https://user-images.githubusercontent.com/17243028/33868082-dd426bf2-df3b-11e7-9550-2608bdaa9a25.png)

Screenshot attached.

Regard,
William

**Comment by gadcam** [comment] 2017-12-12 10:11
Can not reproduce with Firefox 57.0.2, Wappalyzer 5.2.1 (Win 64bit) : I only have HTTP/2 & Google Web Server. Could you explain a bit more into details how to reproduce it ?

**Comment by jvoisin** [comment] 2017-12-12 11:08
I can't reproduce either. What version are you using?

**Comment by gadcam** [comment] 2017-12-24 00:45
I think we can close this one as we do not have enough information and that it seems to be more an interface glitch than something wrong in Wappalyzer.

**Closed** 2017-12-24 01:24 UTC
