### ISSUE TITLE
Checkbox option in settings to have Wappalyser use a static logo

### ISSUE THREAD

**Issue by Georgiel** [AliasIO/Wappalyzer#1222] opened 2016-08-10 09:29 UTC
I rather like wappalyser, but my use case tends to be that I don't recognise the new logo change in many cases and instead just click the logo to see the overlay dropdown.

I'd like to this end the option of turning off the transforming icon and have it stay as the one static icon.

A nice extra option would be static logo with counter circle similar to these 
![image](https://cloud.githubusercontent.com/assets/5931248/17548780/55b626ec-5ee5-11e6-807a-5e8daa1f8e5f.png)

I'm certain there used to be a similar issue but I can't find it.

**Comment by Georgiel** [comment] 2016-09-06 09:41
Is there no interest in adding this as feature?

I know that the options is intentionally minimal, but I don't see how adding one more checkbox will be a problem?

**Comment by AliasIO** [comment] 2016-09-06 23:10
This is a duplicate of #1166. I would like to implement this feature.

**Closed by AliasIO** 2016-09-06 23:10 UTC
