### ISSUE TITLE
Chrome extension give elfinder debug: [error] [elfinder] Impossibile aprire "#"

### ISSUE THREAD

**Issue by LucaMiozzo** [AliasIO/Wappalyzer#2100] opened 2018-02-16 07:59 UTC
When the Extension in enable, 
visiting some websites, they doesn't work.
In console appear the error:
elfinder debug: [error] [elfinder] Impossibile aprire "#"

**Comment by AlexByte** [comment] 2018-02-17 12:35
Give example of site.

**Comment by gadcam** [comment] 2018-02-21 00:27
Looks like an error of https://github.com/Studio-42/elFinder.
I can not reproduce on the demo website https://studio-42.github.io/elFinder/

**Comment by gadcam** [comment] 2018-03-10 08:59
I think we can close this issue.

**Closed** 2018-03-11 01:26 UTC
