### ISSUE TITLE
magento / PHP on gmail

### ISSUE THREAD

**Issue by alepore** [AliasIO/Wappalyzer#978] opened 2015-10-06 13:42 UTC
<img width="244" alt="screen shot 2015-10-06 at 15 30 29" src="https://cloud.githubusercontent.com/assets/557414/10310166/dd603e40-6c40-11e5-832b-781ad60bebc5.png">

**Comment by AliasIO** [comment] 2015-10-24 23:33
Duplicate of #703.

**Closed by AliasIO** 2015-10-24 23:33 UTC
Labels: Bug
