### ISSUE TITLE
Incorrect Wordpress detection

### ISSUE THREAD

**Issue by alexxn** [AliasIO/Wappalyzer#2016] opened 2018-01-14 15:02 UTC
www.wappalyzer.com is unable to detect Wordpress installed on larrr.com correctly.

I suppose this is a bug, because mainpage source code contains a lot of references like wp-content, wp-includes, wp-admin, also mentions "wordpress" directly in meta tags (eg `<meta name="generator" content="WordPress 4.5.12" />`)

**Comment by jvoisin** [comment] 2018-01-14 18:27
It's detected here, I can't reproduce your issue.

**Comment by gadcam** [comment] 2018-01-15 00:15
Last version of Wappalyzer in Firefox I have WordPress with the correct version.

**Comment by alexxn** [comment] 2018-01-15 08:51
Just tried it once again using Chrome Incognito Mode. Nothing is detected.
![1](https://user-images.githubusercontent.com/5682814/34934158-76bdecf2-f9ea-11e7-9b42-aef7228257d3.png)

**Comment by gadcam** [comment] 2018-01-15 11:09
No problem with wappalyzer, you should use the extension https://www.wappalyzer.com/download

I think the website is blocking the request cf
```batch
curl http://larrr.com/

<html><head><title>Error 406 - Not Acceptable</title><head><body><h1>Error 406 - Not Acceptable</h1><p>Generally a 406 error is caused because a request has been blocked by Mod Security. If you believe that your request has been blocked by mistake please contact the web site owner.</p></body></html>
```

**Comment by gadcam** [comment] 2018-01-15 11:19
However you are right it would be cool to display the HTTP return code to understand what is going on or some error message.

**Comment by alexxn** [comment] 2018-01-15 12:09
I thought this is the place for reporting both Wappalyzer extension AND Wappalyzer Website issues.
If it's just for the extension related problem, lets close the issue.

**Comment by AliasIO** [comment] 2018-01-15 22:55
Thanks, @alexxn. This is the right place for issues like this. It should be fixed now, please try it again.

**Closed by AliasIO** 2018-01-15 22:55 UTC

**Comment by alexxn** [comment] 2018-01-16 08:21
Now it works

**Comment by AliasIO** [comment] 2018-01-16 11:14
Perfect, thanks!
