### ISSUE TITLE
Unable to detect Angular 2 and beyond

### ISSUE THREAD

**Issue by rahulbhooteshwar** [AliasIO/Wappalyzer#1800] opened 2017-11-06 10:55 UTC
Wappalyzer is not detecting Angular 2 or beyond on the sites developed purely on Angular 2, 4 or beyond.

**Comment by gadcam** [comment] 2017-11-06 14:38
Can you give us some URLs so we could look into this ?

**Comment by jvoisin** [comment] 2017-11-28 09:21
This is a duplicate of #1605 I think.

**Closed** 2017-12-08 20:28 UTC
