### ISSUE TITLE
Wappalyzer appending json in url if enabled

### ISSUE THREAD

**Issue by madhavprabhu** [AliasIO/Wappalyzer#1407] opened 2017-03-02 11:30 UTC
Hello, 
when we have a normal form submission .
After the wappalyzer plugin is enabled the url is appended with json.
Please have a fix for this issue.

**Comment by craiglondon** [comment] 2017-03-02 12:17
Do you have a screenshot?  Which browser?

**Comment by madhavprabhu** [comment] 2017-03-03 11:32
For your testing please open this url http://www.webbased.com/wordpress-developer.
When wappalyzer plugin is disabled , website opens perfectly without any issue.
But when the plugin is enabled , website opens completely for couple of seconds then refreshes/redirect and all the json will be injected in the url and you can see the same on your browser url bar.

Just for information we are rendering form via iframe , when we remove this form website works perfectly.
There were no issues from last couple of years but recent update on plugin made this issue occured. 
Firefox version 44.0.2 , 51.
Any help would be appreciated.

**Comment by jvoisin** [comment] 2017-03-03 12:15
I can't reproduce your issue here, sorry :/

**Comment by jvoisin** [comment] 2017-03-03 12:23
Ho, wait I actually can !
The url:
```
http://www.webbased.com/wordpress-developer/%7B%22width%22:525,%22height%22:390,%22startTime%22:1488543328704,%22adId%22:%221488543328704-3048660893612%22,%22html5%22:true,%22adSizeMeta%22:null,%22winClickTag%22:null,%22element%22:%7B%22tagName%22:%22BODY%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22class%22:%22wallpaper%22,%22adId%22:%221488543328704-3048660893612%22%7D,%22context%22:%7B%22tagName%22:%22HTML%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22HEAD%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js%22%7D,%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/js/jquery-1.8.2.js%22%7D,%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.js%22%7D]%7D,%7B%22tagName%22:%22BODY%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22FORM%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22UL%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:152,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:152,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:164,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:165,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D,%7B%22tagName%22:%22SPAN%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/refresh2.gif%22%7D],%22class%22:%22form_load_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%22%7D,%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:206,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:206,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:218,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:219,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%22%7D,%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:260,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:260,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:272,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:273,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%20%22%7D],%22class%22:%22form_setting_box%20get_forms_box%22%7D],%22class%22:%22wrapper%20form_stsrt%22%7D],%22id%22:%222891%22,%22class%22:%22form_stsrt%20form_2891%22,%22name%22:%22_2891%22%7D],%22class%22:%22main_form%22%7D],%22class%22:%22pi%20form_wrapper%20container_24%22%7D],%22class%22:%22wallpaper%22,%22adId%22:%221488543328704-3048660893612%22%7D]%7D,%22serializedIframeContents%22:%7B%22tagName%22:%22HTML%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22HEAD%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js%22%7D,%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/js/jquery-1.8.2.js%22%7D,%7B%22tagName%22:%22SCRIPT%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.js%22%7D]%7D,%7B%22tagName%22:%22BODY%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:525,%22height%22:390,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22FORM%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22UL%22,%22width%22:521,%22height%22:0,%22left%22:2,%22top%22:6,%22children%22:[%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:152,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:152,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:164,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:165,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D,%7B%22tagName%22:%22SPAN%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:0,%22height%22:0,%22left%22:0,%22top%22:0,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/refresh2.gif%22%7D],%22class%22:%22form_load_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%22%7D,%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:206,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:206,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:218,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:219,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%22%7D,%7B%22tagName%22:%22LI%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:260,%22children%22:[%7B%22tagName%22:%22DIV%22,%22width%22:521,%22height%22:40,%22left%22:2,%22top%22:260,%22children%22:[%7B%22tagName%22:%22SPAN%22,%22width%22:14,%22height%22:15,%22left%22:503,%22top%22:272,%22children%22:[%7B%22tagName%22:%22IMG%22,%22width%22:14,%22height%22:14,%22left%22:503,%22top%22:273,%22children%22:[],%22url%22:%22https://forms.kpianalyser.com/images/cross.png%22%7D],%22class%22:%22error_img%22%7D],%22class%22:%22form_setting_box_wrapper%22%7D],%22class%22:%22%20aline_top%20%22%7D],%22class%22:%22form_setting_box%20get_forms_box%22%7D],%22class%22:%22wrapper%20form_stsrt%22%7D],%22id%22:%222891%22,%22class%22:%22form_stsrt%20form_2891%22,%22name%22:%22_2891%22%7D],%22class%22:%22main_form%22%7D],%22class%22:%22pi%20form_wrapper%20container_24%22%7D],%22class%22:%22wallpaper%22,%22adId%22:%221488543328704-3048660893612%22%7D]%7D,%22postMessageId%22:%221484952787-11883-24071-12354-1549%22%7D
```

The page content:
```html
You don't have permission to access /wordpress-developer/{"width":525,"height":390,"startTime":1488543328704,"adId":"1488543328704-3048660893612","html5":true,"adSizeMeta":null,"winClickTag":null,"element":{"tagName":"BODY","width":525,"height":390,"left":0,"top":0,"class":"wallpaper","adId":"1488543328704-3048660893612"},"context":{"tagName":"HTML","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"HEAD","width":0,"height":0,"left":0,"top":0,"children":[{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js"},{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://forms.kpianalyser.com/js/jquery-1.8.2.js"},{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.js"}]},{"tagName":"BODY","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"DIV","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"DIV","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"FORM","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"DIV","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"UL","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"LI","width":521,"height":40,"left":2,"top":152,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":152,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":164,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":165,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"},{"tagName":"SPAN","width":0,"height":0,"left":0,"top":0,"children":[{"tagName":"IMG","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://forms.kpianalyser.com/images/refresh2.gif"}],"class":"form_load_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top"},{"tagName":"LI","width":521,"height":40,"left":2,"top":206,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":206,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":218,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":219,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top"},{"tagName":"LI","width":521,"height":40,"left":2,"top":260,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":260,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":272,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":273,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top "}],"class":"form_setting_box get_forms_box"}],"class":"wrapper form_stsrt"}],"id":"2891","class":"form_stsrt form_2891","name":"_2891"}],"class":"main_form"}],"class":"pi form_wrapper container_24"}],"class":"wallpaper","adId":"1488543328704-3048660893612"}]},"serializedIframeContents":{"tagName":"HTML","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"HEAD","width":0,"height":0,"left":0,"top":0,"children":[{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js"},{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://forms.kpianalyser.com/js/jquery-1.8.2.js"},{"tagName":"SCRIPT","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.js"}]},{"tagName":"BODY","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"DIV","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"DIV","width":525,"height":390,"left":0,"top":0,"children":[{"tagName":"FORM","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"DIV","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"UL","width":521,"height":0,"left":2,"top":6,"children":[{"tagName":"LI","width":521,"height":40,"left":2,"top":152,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":152,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":164,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":165,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"},{"tagName":"SPAN","width":0,"height":0,"left":0,"top":0,"children":[{"tagName":"IMG","width":0,"height":0,"left":0,"top":0,"children":[],"url":"https://forms.kpianalyser.com/images/refresh2.gif"}],"class":"form_load_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top"},{"tagName":"LI","width":521,"height":40,"left":2,"top":206,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":206,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":218,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":219,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top"},{"tagName":"LI","width":521,"height":40,"left":2,"top":260,"children":[{"tagName":"DIV","width":521,"height":40,"left":2,"top":260,"children":[{"tagName":"SPAN","width":14,"height":15,"left":503,"top":272,"children":[{"tagName":"IMG","width":14,"height":14,"left":503,"top":273,"children":[],"url":"https://forms.kpianalyser.com/images/cross.png"}],"class":"error_img"}],"class":"form_setting_box_wrapper"}],"class":" aline_top "}],"class":"form_setting_box get_forms_box"}],"class":"wrapper form_stsrt"}],"id":"2891","class":"form_stsrt form_2891","name":"_2891"}],"class":"main_form"}],"class":"pi form_wrapper container_24"}],"class":"wallpaper","adId":"1488543328704-3048660893612"}]},"postMessageId":"1484952787-11883-24071-12354-1549"} on this server.
```

**Comment by madhavprabhu** [comment] 2017-03-03 12:43
Yes this exactly is the issue

**Comment by madhavprabhu** [comment] 2017-03-04 06:09
Any update ?

**Comment by AliasIO** [comment] 2017-03-04 06:22
Will be fixed soon.

**Comment by madhavprabhu** [comment] 2017-03-04 09:01
Please help for the same , it is an urgent basis issue encountered

**Comment by AlexByte** [comment] 2017-03-04 10:32
Page redirected me to `http://www.webbased.com/wordpress-developer/5F50F845_0528_401D_85D5_999E20B13DF5_frms_dsptch@@READY`

**Comment by madhavprabhu** [comment] 2017-03-05 01:43
Any update?

**Comment by jyothibhandari** [comment] 2017-03-05 08:29
Hi,
A quick help or the reason behind the issue could be shared with us would be a great help appreciated.

**Comment by madhavprabhu** [comment] 2017-03-06 07:13
Any update on the issue ? Can we please get the reason as to why it is happening after the addon activation ?

**Comment by madhavprabhu** [comment] 2017-03-06 13:51
Any update on the issue ? It would be a great help if this issue gets fixed.
Thanks

**Comment by jvoisin** [comment] 2017-03-06 14:10
I'm quite sure that spamming the issues tracker every 12 hours is the best way to get this bug fixed, please keep going.

**Comment by craiglondon** [comment] 2017-03-07 12:55
https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/

**Comment by AliasIO** [comment] 2017-03-10 23:41
This should be fixed in the next update, please re-open this thread if the issue persists.

**Closed by AliasIO** 2017-03-10 23:41 UTC
