### ISSUE TITLE
Wappalyzer on Edge (Chromium) crashes right away

### ISSUE THREAD

**Issue by dovidcohen** [AliasIO/wappalyzer#2936] opened 2020-02-10 17:59 UTC
This extension has been great in Chrome and FireFox but now I'm trying out Edge Chromium and it has shown three behavioral problems:

1. At first it ran but didn't update the icon showing in the toolbar with an icon that represented what the given site was running (but clicking on it did show everything it should). 
2. Then it would occasionally crash and not appear at all until I did a "repair" and I'd be back to #1 above
3. Now after a repair or reinstall, it disappears the moment I click on it.

**Comment by sunbuhui7** [comment] 2020-02-17 12:15
+1，it happens to me too

**Comment by AliasIO** [comment] 2020-02-19 22:54
Duplicate of #2927.

**Closed by AliasIO** 2020-02-19 22:54 UTC
