### ISSUE TITLE
Wappalyzer slowing down loading time on websites by 3/4

### ISSUE THREAD

**Issue by si9int** [AliasIO/wappalyzer#3415] opened 2020-10-06 21:52 UTC
**Platform**
Which platform does the bug apply to?
* WebExtension (Mozilla Firefox)
* Website

**Description**
When visiting a website (e.g. wordpress.com; fast-resolving) without wappalyzer enabled the loading-time is reduced by ~70%.
This can be easily measured using the development-tools.

**Expected behavior**
Wappalyzer analyses the **loaded** content and doesn't intercept.

**Comment by AliasIO** [comment] 2020-10-16 20:03
Hi, can you show me what metrics you're looking at? Like a screenshot.

**Comment by saespmar** [comment] 2020-10-16 21:43
Hi! I have noticed a similar problem. I'm using Chrome 86.0.4240.75 (64 bits) and Wappalyzer 6.3.9

I have a folder in my bookmarks with 10 subreddits that I usually open all at once. This has never been a problem, but recently, I have noticed that Chrome is completely unresponsive for a couple of seconds if I do this with Wappalyzer activated. However, if I disable the extension, the 10 tabs load just fine.

So, it looks lke the latest versions of Wappalyzer are affecting the loading times significantly.

**Comment by AliasIO** [comment] 2020-11-08 22:20
Please let me know if this is still an issue in today's update, v6.4.14.

**Comment by kevinoid** [comment] 2020-11-09 17:40
This is still an issue for me with v6.4.14.  For reference, I found that either removing and re-installing Wappalyzer or deleting all its data in [Extension Storage](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Extension_Storage) improve load time significantly.

(I'm able to reliably reproduce the issue using a profile backup if that would be helpful.)

**Comment by saespmar** [comment] 2020-11-10 17:41
The problem was solved for me. Pages load as fast as always with v6.4.14 👌

**Comment by AliasIO** [comment] 2020-11-12 21:38
The issue may have been two-fold, the next release should hopefully fix the storage issue as well.

**Comment by kyletaylored** [comment] 2021-01-12 17:09
Closing for now as the issue seems resolved, unless additional information is provided.

**Closed by kyletaylored** 2021-01-12 17:09 UTC
Labels: Bug
