### ISSUE TITLE
Chrome Extension Bug

### ISSUE THREAD

**Issue by arothweiler** [AliasIO/Wappalyzer#2080] opened 2018-02-09 14:31 UTC
Hey

I created few sites without React, but it always says that it was created with React.
On Firefox it works just fine.

friendly regard

**Comment by AlexByte** [comment] 2018-02-12 21:17
Give example.

**Comment by arothweiler** [comment] 2018-02-12 21:33
if you go to my site: https://www.andrerothweiler.ch you see React as Frameworj and its wrong, with Chrome extension.
But with Firefox same site, works fine!

**Comment by AlexByte** [comment] 2018-02-12 21:35
Not confirmed.
![image](https://user-images.githubusercontent.com/25251772/36120916-c7a9ebee-1055-11e8-80ab-1c5e02cd9751.png)

**Comment by arothweiler** [comment] 2018-02-12 21:38
![bug_wappalyzer](https://user-images.githubusercontent.com/17226956/36121056-6123ef6a-1045-11e8-94b6-46b5788287d7.jpg)

**Comment by arothweiler** [comment] 2018-02-12 21:39
Maybe is just my browser, I just wanted to help!

**Comment by AlexByte** [comment] 2018-02-12 21:39
Try to disable other extensions or try in incognito mode.

**Comment by arothweiler** [comment] 2018-02-12 21:40
Yes, I will, but I use Firefox more. Anyway good day sir :)

**Comment by AliasIO** [comment] 2018-02-23 00:35
Did you ever use React somewhere on that domain? Wappalyzer caches results for some time. Restarting your browser should give you up-to-date results.

**Comment by arothweiler** [comment] 2018-02-23 00:43
Hello

Not at all. I am just starting to learn React. It might be a problem with
other Chrome Applications.

friendly regard

2018-02-23 1:35 GMT+01:00 Elbert Alias <notifications@github.com>:

**Comment by AliasIO** [comment] 2018-02-23 00:54
Could be. I'll close this for now as we can't reproduce it.

**Closed by AliasIO** 2018-02-23 00:54 UTC

**Comment by Voknehzyr** [comment] 2018-03-09 08:25
Looks like I found what causes that problem.
One of your extensions injects React code in your page, looks like there is no way to debug and cancel this.

In my case that extension was **WOT** (https://chrome.google.com/webstore/detail/wot-web-of-trust-website/bhmmomiinigofkjcapegjjndpbikblnp)

**Comment by arothweiler** [comment] 2018-03-09 09:20
Hello Igor, Thank you!

WOT was an issue and it helped.
Thank you for helping me out!


udachi!

2018-03-09 9:25 GMT+01:00 Igor Ryzhenkov <notifications@github.com>:
