### ISSUE TITLE
Wappalyzer stopped working

### ISSUE THREAD

**Issue by amjo** [AliasIO/Wappalyzer#1604] opened 2017-06-10 10:17 UTC
Wappalyzer has stopped working on my Firefox 53.0.3. only Twitter Bootstrap is showing, but other tools wont show. 
has this happened to other people? both my browser and the extension are updated. i want to leave Firefox resetting as a final resort.

**Comment by CristianoNicolaFerreira** [comment] 2017-06-10 14:05
Yes! I'm with this problem.

**Comment by gadcam** [comment] 2017-06-10 15:42
Duplicate of #1601.

**Closed** 2017-11-03 01:45 UTC
