### ISSUE TITLE
Bug on analyzing gandi.net v5 Domain page

### ISSUE THREAD

**Issue by asmoporma** [AliasIO/Wappalyzer#2073] opened 2018-02-07 14:48 UTC
Extension enabled Firefox gets into stucked state for 30-40s. Unable to do anything. I managed to figure out that wappalyzer is the reason.

**Comment by gadcam** [comment] 2018-02-07 16:15
Duplicate of #2061

**Closed** 2018-02-09 01:51 UTC
