### ISSUE TITLE
Wapp's icon being displayed, instead of website platform's icon

### ISSUE THREAD

**Issue by KellanH** [AliasIO/Wappalyzer#1209] opened 2016-07-27 19:34 UTC
Hey Wappalyzer folks,

Ever since my recent updated, I'm seeing your icon in the browser where it used to show the icon on the software being used on a website...
Ex: https://monosnap.com/file/cu69ynWnSrAbJd0bY1LO8eikmgrn5D.png

This website is on our platform - shopify - and not showing our icon. 

Love your extension. Hope we can fix this.

**Comment by AliasIO** [comment] 2016-08-07 00:47
Duplicate of #1168. Chrome doesn't support SVG icons, we'll need to convert them to PNG during build.

**Closed by AliasIO** 2016-08-07 00:47 UTC
