### ISSUE TITLE
Google detected as megento (50%)!

### ISSUE THREAD

**Issue by vahidreza** [AliasIO/Wappalyzer#1003] opened 2015-10-20 19:23 UTC
<img width="1438" alt="screen shot 1394-07-28 at 22 45 30" src="https://cloud.githubusercontent.com/assets/3737551/10622442/810f3ab0-7794-11e5-92e7-fcd5c7d022fc.png">

**Comment by klonos** [comment] 2015-10-20 22:06
@vahidreza you did not give it enough time to upload the screenshot. Try again, but this time leave it do its thing for a few seconds :wink:

**Comment by vahidreza** [comment] 2015-10-20 22:09
hey man
it was some sort of network issue. it timed out several times.
i'll handle it :)

**Comment by AliasIO** [comment] 2015-10-24 23:32
Duplicate of #978.

**Closed by AliasIO** 2015-10-24 23:32 UTC
