### ISSUE TITLE
Show all application icons in the adress bar

### ISSUE THREAD

**Issue by maicol07** [AliasIO/Wappalyzer#2104] opened 2018-02-16 15:43 UTC
Hi,s it possible to show all the icons of the apps in the adress bar instead of only one? (Firefox 58.0.2 x64)
Thanks

**Comment by gadcam** [comment] 2018-02-16 15:57
It used to be possible but it is not anymore.
Now we have to use this API https://developer.mozilla.org/fr/Add-ons/WebExtensions/API/pageAction 
This a duplicate of/This is linked to #1426 & #1541 & #1601 
You can check #1601 to see why it is not possible to work around this limitation.

**Comment by maicol07** [comment] 2018-02-16 16:00
Ok thanks for the info!

**Closed** 2018-02-16 16:00 UTC
