### ISSUE TITLE
Wappalyzer version 4 - browser-polyfill.js uncaught error in promise

### ISSUE THREAD

**Issue by sabeersulaiman** [AliasIO/Wappalyzer#1489] opened 2017-04-01 13:00 UTC
I am getting the following error after updating to the latest version of wappalyzer : 
Uncaught exception (in promise), message : "The message port closed before a reponse was received." in browser-polyfill.js

System Details :
Ubunutu 16.04 amd64 
Chrome Version 56.0.2924.87 (64-bit)
Wappalyzer version 4

**Comment by MannyC** [comment] 2017-04-01 17:00
I get the same error.  Stack trace:
```
callbackArgs @ browser-polyfill.js:590
sendResponseAndClearCallback @ VM565 extensions::messaging:345
disconnectListener @ VM565 extensions::messaging:369
EventImpl.dispatchToListener @ VM558 extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ VM564 extensions::utils:149
EventImpl.dispatch_ @ VM558 extensions::event_bindings:372
EventImpl.dispatch @ VM558 extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ VM564 extensions::utils:149
dispatchOnDisconnect @ VM565 extensions::messaging:306
browser-polyfill.js:590 Uncaught (in promise) Object {message: "The message port closed before a reponse was received."}
callbackArgs @ browser-polyfill.js:590
sendResponseAndClearCallback @ VM565 extensions::messaging:345
disconnectListener @ VM565 extensions::messaging:369
EventImpl.dispatchToListener @ VM558 extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ VM564 extensions::utils:149
EventImpl.dispatch_ @ VM558 extensions::event_bindings:372
EventImpl.dispatch @ VM558 extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ VM564 extensions::utils:149
dispatchOnDisconnect @ VM565 extensions::messaging:306
```

Also Ubuntu 16.04, amd64, Chrome Version 57.0.2987.110 (64-bit).  

It breaks the Event Listeners panel in devtools.

**Comment by MannyC** [comment] 2017-04-01 17:01
Oh, I see this is a duplicate of #1487

**Comment by emaxedon** [comment] 2017-04-01 18:09
Bump. I'm getting the same issue.

**Closed** 2017-04-01 22:23 UTC
