### ISSUE TITLE
Black shadow

### ISSUE THREAD

**Issue by Sina-Soltani** [AliasIO/Wappalyzer#2085] opened 2018-02-12 21:11 UTC
Sometimes there is a black shadow on Wappalyzer when I scroll on it.
I use Firefox v58.

![wappalyzer bug](https://user-images.githubusercontent.com/10329804/36119990-03a600e2-1042-11e8-93c9-c72be8c19806.png)

**Comment by gadcam** [comment] 2018-02-12 23:30
Duplicate of #1937.
Is it an issue of Firefox cf https://github.com/AliasIO/Wappalyzer/issues/1937#issuecomment-352584900.
I you want to help you can upvote the issue in the mozilla bug tracker (cf comment)

**Closed** 2018-02-23 00:35 UTC
